version: '3.9'

services:
  postgresql:
    container_name: helpy_db
    image: postgres:13-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: helpy
      POSTGRES_PASSWORD: helpypg
      POSTGRES_DB: helpydb
    networks:
      - helpy

  api:
    container_name: helpy_api
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - helpy
    ports:
      - '5590:5590'

networks:
  helpy:
    driver: bridge

volumes:
  dbdata:
