version: '3.9'

services:
  postgresql:
    container_name: helpy-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: helpy
      POSTGRES_PASSWORD: helpypg
      POSTGRES_DB: helpydb
    networks:
      - helpy

  api:
    container_name: helpy-api
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - helpy
    ports:
      - '$PORT:$PORT'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

networks:
  helpy:
    driver: bridge

volumes:
  dbdata:
  esdata:
