version: '3.9'

services:
  postgresql:
    container_name: lux_db
    image: postgres:13-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lux
      POSTGRES_PASSWORD: luxpg
      POSTGRES_DB: luxdb
    networks:
      - lux

  api:
    container_name: lux_api
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - lux
    ports:
      - '5590:5590'

networks:
  lux:
    driver: bridge

volumes:
  dbdata:
